# Generated by Django 2.1.7 on 2019-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter_table',
            name='date',
            field=models.IntegerField(),
        ),
    ]
